repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0  # Use the latest version
    hooks:
      - id: black
        args: ["--line-length=120"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.44.0  # Use the latest version
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.3  # Use the latest version
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: git-add
        name: Git Add
        entry: git add .
        language: system
        stages: [pre-commit]