"""Created route-component and user-component association model

Revision ID: df124a7ab0bf
Revises: 74851e15e08f
Create Date: 2025-07-16 15:15:45.901452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df124a7ab0bf'
down_revision: Union[str, None] = '74851e15e08f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_component',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('component_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'component_id')
    )
    op.create_table('route_component',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('route_id', 'component_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_component')
    op.drop_table('user_component')
    # ### end Alembic commands ###
